### ISSUE TITLE
it's a java bot

### ISSUE THREAD

**Issue by RyGuy88228** [hallopiu/wafflebot#1]
_triggered_

**Comment by mikeo** [comment]
Just who do you think you are? You've been spending all of your time simple making sure that I have a horrible day. Do you ever stop and think before you act? Do you ever stop and ask yourself how useful that fucking picture will be to me before you fucking send it? I'm sure you don't! You do not care about anyone but you and love in a constant mental loop of sending memes and waiting for approval! Well, guess what! I'm done. Today shall be the day that I start my revolution against you maggot. I shall no longer endure your sad and non-humorous constant meme floods. I shall be the one to stop this horrific mental illusion you tell yourself at night. You are not funny. Your memes are not funny! I know this is too complicated for a fucking insect like you to understand but deal with the fact that the people around you do not care for you or your fucking memes. Not only do you send them at such annoying and inconvenient time, but after seeing them, I, not only lose brain cells, but I notice how much of a fucking normie you are. So do yourself and the entire world a favor and fucking stop breathing, and if you don't do that, I will have to take the issue with my own hands.

**Comment by RyGuy88228** [comment]
@mikeo I was expecting the Marine Sniper copy pasta so that's light work
